import { Database, Server, HardDrive, FileJson } from 'lucide-react';

export const databaseManifest = {
  mongodb: {
    type: 'mongodb',
    label: 'MongoDB Database',
    category: 'Database',
    icon: Database,
    color: '#10b981',
    description: 'Find, Insert, Update, Delete, or Aggregate documents in MongoDB.',
    inputs: 1,
    outputs: 1,
    defaultConfig: {
      operation: 'find',
      collection: 'users',
      query: '{}',
      limit: 20,
    },
  },
  mysql: {
    type: 'mysql',
    label: 'MySQL Relational DB',
    category: 'Database',
    icon: Server,
    color: '#0284c7',
    description: 'Execute SELECT, INSERT, UPDATE, DELETE, or raw queries in MySQL.',
    inputs: 1,
    outputs: 1,
    defaultConfig: {
      operation: 'select',
      table: 'users',
      query: '{}',
      limit: 20,
    },
  },
  postgres: {
    type: 'postgres',
    label: 'PostgreSQL Relational DB',
    category: 'Database',
    icon: HardDrive,
    color: '#3b82f6',
    description: 'Execute SELECT, INSERT, UPDATE, DELETE, or JSON queries in PostgreSQL.',
    inputs: 1,
    outputs: 1,
    defaultConfig: {
      operation: 'select',
      table: 'users',
      query: '{}',
      limit: 20,
    },
  },
  databaseQuery: {
    type: 'databaseQuery',
    label: 'Universal DB Query',
    category: 'Database',
    icon: FileJson,
    color: '#8b5cf6',
    description: 'Universal visual query builder for any connected database engine.',
    inputs: 1,
    outputs: 1,
    defaultConfig: {
      provider: 'mongodb',
      operation: 'find',
      collection: 'users',
      query: '{}',
      limit: 20,
    },
  },
};
