import { Database, PlusCircle, Search, FileText, Edit3, Trash2, Hash, Layers } from 'lucide-react';

export const mongoCrudManifest = {
  mongoInsertOne: {
    type: 'mongoInsertOne',
    label: 'MongoDB Insert One',
    category: 'Database',
    icon: PlusCircle,
    color: '#10b981',
    description: 'Inserts a single document payload into a MongoDB collection.',
    inputs: 1,
    outputs: 1,
    defaultConfig: {
      credentialId: '',
      database: 'automatex',
      collection: 'users',
      document: '{\n  "name": "{{trigger.body.name}}",\n  "email": "{{trigger.body.email}}"\n}',
    },
  },
  mongoFind: {
    type: 'mongoFind',
    label: 'MongoDB Find',
    category: 'Database',
    icon: Search,
    color: '#10b981',
    description: 'Finds multiple documents matching query filter criteria.',
    inputs: 1,
    outputs: 1,
    defaultConfig: {
      credentialId: '',
      database: 'automatex',
      collection: 'users',
      filter: '{\n  "status": "active"\n}',
      limit: 50,
    },
  },
  mongoFindOne: {
    type: 'mongoFindOne',
    label: 'MongoDB Find One',
    category: 'Database',
    icon: FileText,
    color: '#10b981',
    description: 'Finds a single document matching query filter criteria.',
    inputs: 1,
    outputs: 1,
    defaultConfig: {
      credentialId: '',
      database: 'automatex',
      collection: 'users',
      filter: '{\n  "email": "{{trigger.body.email}}"\n}',
    },
  },
  mongoUpdateOne: {
    type: 'mongoUpdateOne',
    label: 'MongoDB Update One',
    category: 'Database',
    icon: Edit3,
    color: '#10b981',
    description: 'Updates a single document matching filter criteria.',
    inputs: 1,
    outputs: 1,
    defaultConfig: {
      credentialId: '',
      database: 'automatex',
      collection: 'users',
      filter: '{\n  "_id": "{{trigger.body.id}}"\n}',
      update: '{\n  "$set": {\n    "status": "verified"\n  }\n}',
    },
  },
  mongoDeleteOne: {
    type: 'mongoDeleteOne',
    label: 'MongoDB Delete One',
    category: 'Database',
    icon: Trash2,
    color: '#10b981',
    description: 'Deletes a single document matching query filter criteria.',
    inputs: 1,
    outputs: 1,
    defaultConfig: {
      credentialId: '',
      database: 'automatex',
      collection: 'users',
      filter: '{\n  "_id": "{{trigger.body.id}}"\n}',
    },
  },
  mongoCount: {
    type: 'mongoCount',
    label: 'MongoDB Count',
    category: 'Database',
    icon: Hash,
    color: '#10b981',
    description: 'Counts documents matching specified filter criteria.',
    inputs: 1,
    outputs: 1,
    defaultConfig: {
      credentialId: '',
      database: 'automatex',
      collection: 'users',
      filter: '{\n  "status": "active"\n}',
    },
  },
  mongoAggregate: {
    type: 'mongoAggregate',
    label: 'MongoDB Aggregate',
    category: 'Database',
    icon: Layers,
    color: '#10b981',
    description: 'Runs an aggregation pipeline query against a MongoDB collection.',
    inputs: 1,
    outputs: 1,
    defaultConfig: {
      credentialId: '',
      database: 'automatex',
      collection: 'orders',
      pipeline: '[\n  {\n    "$match": { "status": "completed" }\n  },\n  {\n    "$group": { "_id": "$user", "total": { "$sum": "$amount" } }\n  }\n]',
    },
  },
};
