import { GoogleSheetsIcon } from './GoogleSheetsIcons';

export const GOOGLE_SHEETS_NODE_TYPES = {
  TRIGGER_WATCH_ROWS: 'googleSheetsTriggerWatchRows',
  READ_ROWS: 'googleSheetsReadRows',
  FIND_ROW: 'googleSheetsFindRow',
  APPEND_ROW: 'googleSheetsAppendRow',
  UPDATE_ROW: 'googleSheetsUpdateRow',
  DELETE_ROW: 'googleSheetsDeleteRow',
  CLEAR_RANGE: 'googleSheetsClearRange',
  BATCH_UPDATE: 'googleSheetsBatchUpdate',
  CREATE_SPREADSHEET: 'googleSheetsCreateSpreadsheet',
  CREATE_WORKSHEET: 'googleSheetsCreateWorksheet',
  DUPLICATE_WORKSHEET: 'googleSheetsDuplicateWorksheet',
  DELETE_WORKSHEET: 'googleSheetsDeleteWorksheet',
  GET_SPREADSHEET_INFO: 'googleSheetsGetSpreadsheetInfo',
};

export const googleSheetsCategory = {
  name: 'Google Sheets',
  icon: GoogleSheetsIcon,
  color: '#34A853',
  description: 'Read, write, update, and automate Google Sheets.',
};

export const googleSheetsNodeDefinitions = {
  [GOOGLE_SHEETS_NODE_TYPES.TRIGGER_WATCH_ROWS]: {
    type: GOOGLE_SHEETS_NODE_TYPES.TRIGGER_WATCH_ROWS,
    category: 'Google Sheets',
    label: 'Google Sheets Trigger',
    description: 'Triggers workflow when a new row, updated row, or deleted row is detected',
    icon: GoogleSheetsIcon,
    color: '#34A853',
    badgeColor: 'bg-emerald-500/10 text-emerald-400 border-emerald-500/20',
    defaultConfig: { triggerType: 'watchNewRow', pollIntervalMs: 60000 },
  },
  [GOOGLE_SHEETS_NODE_TYPES.READ_ROWS]: {
    type: GOOGLE_SHEETS_NODE_TYPES.READ_ROWS,
    category: 'Google Sheets',
    label: 'Read Rows',
    description: 'Read rows from a Google Sheet range into JSON format',
    icon: GoogleSheetsIcon,
    color: '#34A853',
    badgeColor: 'bg-emerald-500/10 text-emerald-400 border-emerald-500/20',
    defaultConfig: { range: 'A1:Z100', headerRow: 1, limit: 0, offset: 0, filterEmpty: true },
  },
  [GOOGLE_SHEETS_NODE_TYPES.FIND_ROW]: {
    type: GOOGLE_SHEETS_NODE_TYPES.FIND_ROW,
    category: 'Google Sheets',
    label: 'Find Row',
    description: 'Search row by Exact Match, Contains, Starts With, Ends With, or Regex',
    icon: GoogleSheetsIcon,
    color: '#34A853',
    badgeColor: 'bg-emerald-500/10 text-emerald-400 border-emerald-500/20',
    defaultConfig: { searchColumn: 'A', searchValue: '', matchType: 'exact' },
  },
  [GOOGLE_SHEETS_NODE_TYPES.APPEND_ROW]: {
    type: GOOGLE_SHEETS_NODE_TYPES.APPEND_ROW,
    category: 'Google Sheets',
    label: 'Append Row',
    description: 'Append new row with automatic column detection and variable mapping',
    icon: GoogleSheetsIcon,
    color: '#34A853',
    badgeColor: 'bg-emerald-500/10 text-emerald-400 border-emerald-500/20',
    defaultConfig: { range: 'Sheet1!A1', mappings: [] },
  },
  [GOOGLE_SHEETS_NODE_TYPES.UPDATE_ROW]: {
    type: GOOGLE_SHEETS_NODE_TYPES.UPDATE_ROW,
    category: 'Google Sheets',
    label: 'Update Row',
    description: 'Update row by specific Row Number or Search Column value',
    icon: GoogleSheetsIcon,
    color: '#34A853',
    badgeColor: 'bg-emerald-500/10 text-emerald-400 border-emerald-500/20',
    defaultConfig: { rowNumber: 2, mappings: [] },
  },
  [GOOGLE_SHEETS_NODE_TYPES.DELETE_ROW]: {
    type: GOOGLE_SHEETS_NODE_TYPES.DELETE_ROW,
    category: 'Google Sheets',
    label: 'Delete Row',
    description: 'Delete row by Row Number or Search value',
    icon: GoogleSheetsIcon,
    color: '#34A853',
    badgeColor: 'bg-emerald-500/10 text-emerald-400 border-emerald-500/20',
    defaultConfig: { rowNumber: 2 },
  },
  [GOOGLE_SHEETS_NODE_TYPES.CLEAR_RANGE]: {
    type: GOOGLE_SHEETS_NODE_TYPES.CLEAR_RANGE,
    category: 'Google Sheets',
    label: 'Clear Range',
    description: 'Clear cell values within range selection',
    icon: GoogleSheetsIcon,
    color: '#34A853',
    badgeColor: 'bg-emerald-500/10 text-emerald-400 border-emerald-500/20',
    defaultConfig: { range: 'Sheet1!A2:Z100' },
  },
  [GOOGLE_SHEETS_NODE_TYPES.BATCH_UPDATE]: {
    type: GOOGLE_SHEETS_NODE_TYPES.BATCH_UPDATE,
    category: 'Google Sheets',
    label: 'Batch Update',
    description: 'Batch update multiple rows or ranges in a single API request',
    icon: GoogleSheetsIcon,
    color: '#34A853',
    badgeColor: 'bg-emerald-500/10 text-emerald-400 border-emerald-500/20',
    defaultConfig: { requests: [] },
  },
  [GOOGLE_SHEETS_NODE_TYPES.CREATE_SPREADSHEET]: {
    type: GOOGLE_SHEETS_NODE_TYPES.CREATE_SPREADSHEET,
    category: 'Google Sheets',
    label: 'Create Spreadsheet',
    description: 'Create a new Google Spreadsheet in Drive folder',
    icon: GoogleSheetsIcon,
    color: '#34A853',
    badgeColor: 'bg-emerald-500/10 text-emerald-400 border-emerald-500/20',
    defaultConfig: { title: 'New Spreadsheet', sheetName: 'Sheet1' },
  },
  [GOOGLE_SHEETS_NODE_TYPES.CREATE_WORKSHEET]: {
    type: GOOGLE_SHEETS_NODE_TYPES.CREATE_WORKSHEET,
    category: 'Google Sheets',
    label: 'Create Worksheet',
    description: 'Add a new worksheet tab inside an existing spreadsheet',
    icon: GoogleSheetsIcon,
    color: '#34A853',
    badgeColor: 'bg-emerald-500/10 text-emerald-400 border-emerald-500/20',
    defaultConfig: { sheetName: 'New Sheet' },
  },
  [GOOGLE_SHEETS_NODE_TYPES.DUPLICATE_WORKSHEET]: {
    type: GOOGLE_SHEETS_NODE_TYPES.DUPLICATE_WORKSHEET,
    category: 'Google Sheets',
    label: 'Duplicate Worksheet',
    description: 'Duplicate an existing worksheet tab',
    icon: GoogleSheetsIcon,
    color: '#34A853',
    badgeColor: 'bg-emerald-500/10 text-emerald-400 border-emerald-500/20',
    defaultConfig: { sourceSheetId: 0, newSheetName: 'Copied Sheet' },
  },
  [GOOGLE_SHEETS_NODE_TYPES.DELETE_WORKSHEET]: {
    type: GOOGLE_SHEETS_NODE_TYPES.DELETE_WORKSHEET,
    category: 'Google Sheets',
    label: 'Delete Worksheet',
    description: 'Delete a worksheet tab from a spreadsheet',
    icon: GoogleSheetsIcon,
    color: '#34A853',
    badgeColor: 'bg-emerald-500/10 text-emerald-400 border-emerald-500/20',
    defaultConfig: { sheetId: 0 },
  },
  [GOOGLE_SHEETS_NODE_TYPES.GET_SPREADSHEET_INFO]: {
    type: GOOGLE_SHEETS_NODE_TYPES.GET_SPREADSHEET_INFO,
    category: 'Google Sheets',
    label: 'Get Spreadsheet Info',
    description: 'Retrieve metadata, worksheet list, and properties',
    icon: GoogleSheetsIcon,
    color: '#34A853',
    badgeColor: 'bg-emerald-500/10 text-emerald-400 border-emerald-500/20',
    defaultConfig: {},
  },
};
