import { GoogleSheetsIcon } from './GoogleSheetsIcons';
import { googleSheetsValidator } from './googleSheetsValidator';

export const GOOGLE_SHEETS_NODE_TYPES = {
  TRIGGER_WATCH_ROWS: 'googleSheetsTriggerWatchRows',
  READ_ROWS: 'googleSheetsReadRows',
  FIND_ROW: 'googleSheetsFindRow',
  APPEND_ROW: 'googleSheetsAppendRow',
  UPDATE_ROW: 'googleSheetsUpdateRow',
  DELETE_ROW: 'googleSheetsDeleteRow',
  CLEAR_RANGE: 'googleSheetsClearRange',
  BATCH_UPDATE: 'googleSheetsBatchUpdate',
  CREATE_SPREADSHEET: 'googleSheetsCreateSpreadsheet',
  CREATE_WORKSHEET: 'googleSheetsCreateWorksheet',
  DUPLICATE_WORKSHEET: 'googleSheetsDuplicateWorksheet',
  DELETE_WORKSHEET: 'googleSheetsDeleteWorksheet',
  GET_SPREADSHEET_INFO: 'googleSheetsGetSpreadsheetInfo',
};

export const googleSheetsCategory = {
  name: 'Google Sheets',
  icon: GoogleSheetsIcon,
  color: '#34A853',
  description: 'Read, write, update, and automate Google Sheets.',
};

export const googleSheetsConfigSchema = [
  { name: 'credentialId', label: 'Google Account Credential', type: 'select', description: 'Select connected Google account' },
  { name: 'spreadsheetId', label: 'Spreadsheet', type: 'select', description: 'Select Google Spreadsheet from Drive' },
  { name: 'worksheet', label: 'Worksheet (Tab)', type: 'select', description: 'Select Worksheet tab (e.g. Sheet1)' },
  { name: 'range', label: 'Cell Range', type: 'text', placeholder: 'A1:Z100', description: 'Cell range selection' },
  { name: 'headerRow', label: 'Header Row', type: 'number', default: 1 },
];

export const googleSheetsNodeDefinitions = {
  [GOOGLE_SHEETS_NODE_TYPES.TRIGGER_WATCH_ROWS]: {
    id: GOOGLE_SHEETS_NODE_TYPES.TRIGGER_WATCH_ROWS,
    type: GOOGLE_SHEETS_NODE_TYPES.TRIGGER_WATCH_ROWS,
    category: 'Google Sheets',
    label: 'Google Sheets Trigger',
    displayName: 'Google Sheets Trigger',
    description: 'Triggers workflow when a new row, updated row, or deleted row is detected',
    icon: GoogleSheetsIcon,
    color: '#34A853',
    badgeColor: 'bg-emerald-500/10 text-emerald-400 border-emerald-500/20',
    defaultConfig: { credentialId: '', spreadsheetId: '', worksheet: 'Sheet1', triggerType: 'watchNewRow', pollIntervalMs: 60000 },
    configSchema: googleSheetsConfigSchema,
    validate: googleSheetsValidator,
  },
  [GOOGLE_SHEETS_NODE_TYPES.READ_ROWS]: {
    id: GOOGLE_SHEETS_NODE_TYPES.READ_ROWS,
    type: GOOGLE_SHEETS_NODE_TYPES.READ_ROWS,
    category: 'Google Sheets',
    label: 'Read Rows',
    displayName: 'Read Rows',
    description: 'Read rows from a Google Sheet range into JSON format',
    icon: GoogleSheetsIcon,
    color: '#34A853',
    badgeColor: 'bg-emerald-500/10 text-emerald-400 border-emerald-500/20',
    defaultConfig: { credentialId: '', spreadsheetId: '', worksheet: 'Sheet1', range: 'A1:Z100', headerRow: 1, limit: 0, offset: 0, filterEmpty: true },
    configSchema: googleSheetsConfigSchema,
    validate: googleSheetsValidator,
  },
  [GOOGLE_SHEETS_NODE_TYPES.FIND_ROW]: {
    id: GOOGLE_SHEETS_NODE_TYPES.FIND_ROW,
    type: GOOGLE_SHEETS_NODE_TYPES.FIND_ROW,
    category: 'Google Sheets',
    label: 'Find Row',
    displayName: 'Find Row',
    description: 'Search row by Exact Match, Contains, Starts With, Ends With, or Regex',
    icon: GoogleSheetsIcon,
    color: '#34A853',
    badgeColor: 'bg-emerald-500/10 text-emerald-400 border-emerald-500/20',
    defaultConfig: { credentialId: '', spreadsheetId: '', worksheet: 'Sheet1', searchColumn: 'A', searchValue: '', matchType: 'exact' },
    configSchema: googleSheetsConfigSchema,
    validate: googleSheetsValidator,
  },
  [GOOGLE_SHEETS_NODE_TYPES.APPEND_ROW]: {
    id: GOOGLE_SHEETS_NODE_TYPES.APPEND_ROW,
    type: GOOGLE_SHEETS_NODE_TYPES.APPEND_ROW,
    category: 'Google Sheets',
    label: 'Append Row',
    displayName: 'Append Row',
    description: 'Append new row with automatic column detection and variable mapping',
    icon: GoogleSheetsIcon,
    color: '#34A853',
    badgeColor: 'bg-emerald-500/10 text-emerald-400 border-emerald-500/20',
    defaultConfig: { credentialId: '', spreadsheetId: '', worksheet: 'Sheet1', range: 'Sheet1!A1', mappings: [] },
    configSchema: googleSheetsConfigSchema,
    validate: googleSheetsValidator,
  },
  [GOOGLE_SHEETS_NODE_TYPES.UPDATE_ROW]: {
    id: GOOGLE_SHEETS_NODE_TYPES.UPDATE_ROW,
    type: GOOGLE_SHEETS_NODE_TYPES.UPDATE_ROW,
    category: 'Google Sheets',
    label: 'Update Row',
    displayName: 'Update Row',
    description: 'Update row by specific Row Number or Search Column value',
    icon: GoogleSheetsIcon,
    color: '#34A853',
    badgeColor: 'bg-emerald-500/10 text-emerald-400 border-emerald-500/20',
    defaultConfig: { credentialId: '', spreadsheetId: '', worksheet: 'Sheet1', rowNumber: 2, mappings: [] },
    configSchema: googleSheetsConfigSchema,
    validate: googleSheetsValidator,
  },
  [GOOGLE_SHEETS_NODE_TYPES.DELETE_ROW]: {
    id: GOOGLE_SHEETS_NODE_TYPES.DELETE_ROW,
    type: GOOGLE_SHEETS_NODE_TYPES.DELETE_ROW,
    category: 'Google Sheets',
    label: 'Delete Row',
    displayName: 'Delete Row',
    description: 'Delete row by Row Number or Search value',
    icon: GoogleSheetsIcon,
    color: '#34A853',
    badgeColor: 'bg-emerald-500/10 text-emerald-400 border-emerald-500/20',
    defaultConfig: { credentialId: '', spreadsheetId: '', worksheet: 'Sheet1', rowNumber: 2 },
    configSchema: googleSheetsConfigSchema,
    validate: googleSheetsValidator,
  },
  [GOOGLE_SHEETS_NODE_TYPES.CLEAR_RANGE]: {
    id: GOOGLE_SHEETS_NODE_TYPES.CLEAR_RANGE,
    type: GOOGLE_SHEETS_NODE_TYPES.CLEAR_RANGE,
    category: 'Google Sheets',
    label: 'Clear Range',
    displayName: 'Clear Range',
    description: 'Clear cell values within range selection',
    icon: GoogleSheetsIcon,
    color: '#34A853',
    badgeColor: 'bg-emerald-500/10 text-emerald-400 border-emerald-500/20',
    defaultConfig: { credentialId: '', spreadsheetId: '', worksheet: 'Sheet1', range: 'Sheet1!A2:Z100' },
    configSchema: googleSheetsConfigSchema,
    validate: googleSheetsValidator,
  },
  [GOOGLE_SHEETS_NODE_TYPES.BATCH_UPDATE]: {
    id: GOOGLE_SHEETS_NODE_TYPES.BATCH_UPDATE,
    type: GOOGLE_SHEETS_NODE_TYPES.BATCH_UPDATE,
    category: 'Google Sheets',
    label: 'Batch Update',
    displayName: 'Batch Update',
    description: 'Batch update multiple rows or ranges in a single API request',
    icon: GoogleSheetsIcon,
    color: '#34A853',
    badgeColor: 'bg-emerald-500/10 text-emerald-400 border-emerald-500/20',
    defaultConfig: { credentialId: '', spreadsheetId: '', worksheet: 'Sheet1', requests: [] },
    configSchema: googleSheetsConfigSchema,
    validate: googleSheetsValidator,
  },
  [GOOGLE_SHEETS_NODE_TYPES.CREATE_SPREADSHEET]: {
    id: GOOGLE_SHEETS_NODE_TYPES.CREATE_SPREADSHEET,
    type: GOOGLE_SHEETS_NODE_TYPES.CREATE_SPREADSHEET,
    category: 'Google Sheets',
    label: 'Create Spreadsheet',
    displayName: 'Create Spreadsheet',
    description: 'Create a new Google Spreadsheet in Drive folder',
    icon: GoogleSheetsIcon,
    color: '#34A853',
    badgeColor: 'bg-emerald-500/10 text-emerald-400 border-emerald-500/20',
    defaultConfig: { credentialId: '', title: 'New Spreadsheet', sheetName: 'Sheet1' },
    configSchema: googleSheetsConfigSchema,
    validate: googleSheetsValidator,
  },
  [GOOGLE_SHEETS_NODE_TYPES.CREATE_WORKSHEET]: {
    id: GOOGLE_SHEETS_NODE_TYPES.CREATE_WORKSHEET,
    type: GOOGLE_SHEETS_NODE_TYPES.CREATE_WORKSHEET,
    category: 'Google Sheets',
    label: 'Create Worksheet',
    displayName: 'Create Worksheet',
    description: 'Add a new worksheet tab inside an existing spreadsheet',
    icon: GoogleSheetsIcon,
    color: '#34A853',
    badgeColor: 'bg-emerald-500/10 text-emerald-400 border-emerald-500/20',
    defaultConfig: { credentialId: '', spreadsheetId: '', sheetName: 'New Sheet' },
    configSchema: googleSheetsConfigSchema,
    validate: googleSheetsValidator,
  },
  [GOOGLE_SHEETS_NODE_TYPES.DUPLICATE_WORKSHEET]: {
    id: GOOGLE_SHEETS_NODE_TYPES.DUPLICATE_WORKSHEET,
    type: GOOGLE_SHEETS_NODE_TYPES.DUPLICATE_WORKSHEET,
    category: 'Google Sheets',
    label: 'Duplicate Worksheet',
    displayName: 'Duplicate Worksheet',
    description: 'Duplicate an existing worksheet tab',
    icon: GoogleSheetsIcon,
    color: '#34A853',
    badgeColor: 'bg-emerald-500/10 text-emerald-400 border-emerald-500/20',
    defaultConfig: { credentialId: '', spreadsheetId: '', sourceSheetId: 0, newSheetName: 'Copied Sheet' },
    configSchema: googleSheetsConfigSchema,
    validate: googleSheetsValidator,
  },
  [GOOGLE_SHEETS_NODE_TYPES.DELETE_WORKSHEET]: {
    id: GOOGLE_SHEETS_NODE_TYPES.DELETE_WORKSHEET,
    type: GOOGLE_SHEETS_NODE_TYPES.DELETE_WORKSHEET,
    category: 'Google Sheets',
    label: 'Delete Worksheet',
    displayName: 'Delete Worksheet',
    description: 'Delete a worksheet tab from a spreadsheet',
    icon: GoogleSheetsIcon,
    color: '#34A853',
    badgeColor: 'bg-emerald-500/10 text-emerald-400 border-emerald-500/20',
    defaultConfig: { credentialId: '', spreadsheetId: '', worksheet: '' },
    requiresColumns: false,
    supportsColumnMapping: false,
    configSchema: googleSheetsConfigSchema,
    validate: googleSheetsValidator,
  },
  [GOOGLE_SHEETS_NODE_TYPES.GET_SPREADSHEET_INFO]: {
    id: GOOGLE_SHEETS_NODE_TYPES.GET_SPREADSHEET_INFO,
    type: GOOGLE_SHEETS_NODE_TYPES.GET_SPREADSHEET_INFO,
    category: 'Google Sheets',
    label: 'Get Spreadsheet Info',
    displayName: 'Get Spreadsheet Info',
    description: 'Retrieve metadata, worksheet list, and properties',
    icon: GoogleSheetsIcon,
    color: '#34A853',
    badgeColor: 'bg-emerald-500/10 text-emerald-400 border-emerald-500/20',
    defaultConfig: { credentialId: '', spreadsheetId: '' },
    configSchema: googleSheetsConfigSchema,
    validate: googleSheetsValidator,
  },
};
