/**
 * CredentialValidator.js
 * Validates credential requirements for nodes generated by the AI Builder.
 * Prevents broken workflows and directs the user to connect integrations safely.
 */

import { CapabilityRegistry } from './CapabilityRegistry.js';

export class CredentialValidator {
  /**
   * Check if all required credentials exist for the planned nodes
   * @param {Array<string>} nodeTypes - Array of nodeType strings
   * @param {Object} userCredentials - Available credentials map or array
   * @returns {Object} { isValid, missingCredentials, requiredIntegrations }
   */
  static validate(nodeTypes = [], userCredentials = {}) {
    const missing = new Set();
    const required = new Set();

    nodeTypes.forEach((type) => {
      const spec = CapabilityRegistry.getNodeSpec(type);
      if (spec && spec.requiredCredentials) {
        spec.requiredCredentials.forEach((cred) => {
          required.add(cred);
          // Check if credential is present in userCredentials
          const hasCred = this.hasCredential(cred, userCredentials);
          if (!hasCred) {
            missing.add(cred);
          }
        });
      }
    });

    const missingList = Array.from(missing);
    const requiredList = Array.from(required);

    return {
      isValid: missingList.length === 0,
      missingCredentials: missingList,
      requiredIntegrations: requiredList,
      guidance: missingList.map((cred) => this.getCredentialGuidance(cred)),
    };
  }

  static hasCredential(credName, userCredentials) {
    if (!userCredentials) return true; // Default to true in offline preview unless explicitly passed

    if (Array.isArray(userCredentials)) {
      return userCredentials.some((c) => (c.type || c.provider || c.name || '').toLowerCase() === credName.toLowerCase());
    }

    if (typeof userCredentials === 'object') {
      return Boolean(userCredentials[credName] || userCredentials[credName.toLowerCase()]);
    }

    return true;
  }

  static getCredentialGuidance(credName) {
    const credLower = credName.toLowerCase();
    switch (credLower) {
      case 'github':
        return {
          type: 'github',
          label: 'GitHub Connection',
          action: 'Connect GitHub Account',
          route: '/settings/integrations/github',
        };
      case 'discord':
        return {
          type: 'discord',
          label: 'Discord Bot Token / Webhook',
          action: 'Connect Discord',
          route: '/settings/integrations/discord',
        };
      case 'google':
      case 'gmail':
        return {
          type: 'google',
          label: 'Google OAuth Account',
          action: 'Connect Google',
          route: '/settings/integrations/google',
        };
      case 'mongodb':
        return {
          type: 'mongodb',
          label: 'MongoDB Connection URI',
          action: 'Configure MongoDB',
          route: '/settings/integrations/mongodb',
        };
      default:
        return {
          type: credName,
          label: `${credName} Credential`,
          action: `Connect ${credName}`,
          route: `/settings/integrations/${credName}`,
        };
    }
  }
}
