export const EXECUTION_STATUS = {
  PENDING: 'PENDING',
  RUNNING: 'RUNNING',
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED',
  CANCELLED: 'CANCELLED'
};

export const NODE_TYPES = {
  // Triggers
  MANUAL_TRIGGER: 'MANUAL_TRIGGER',
  WEBHOOK_TRIGGER: 'WEBHOOK_TRIGGER',
  SCHEDULE_TRIGGER: 'SCHEDULE_TRIGGER',

  // Actions
  HTTP_REQUEST: 'HTTP_REQUEST',
  DELAY: 'DELAY',
  CODE_TRANSFORM: 'CODE_TRANSFORM',
  CONDITION: 'CONDITION',
  LOG_ACTION: 'LOG_ACTION'
};

export const NODE_CATEGORY = {
  TRIGGER: 'TRIGGER',
  ACTION: 'ACTION',
  LOGIC: 'LOGIC'
};
