import {
  Zap,
  Webhook,
  Clock,
  Globe,
  Hourglass,
  Code,
  GitBranch,
  Terminal,
  FileOutput,
  MessageSquare,
  FolderPlus,
  Trash2,
  ShieldPlus,
  ShieldX,
  UserPlus,
  UserMinus,
} from 'lucide-react';

export const NODE_TYPES = {
  // Triggers
  MANUAL_TRIGGER: 'MANUAL_TRIGGER',
  WEBHOOK_TRIGGER: 'WEBHOOK_TRIGGER',
  SCHEDULE_TRIGGER: 'SCHEDULE_TRIGGER',

  // Actions
  HTTP_REQUEST: 'HTTP_REQUEST',
  DELAY: 'DELAY',
  CODE_TRANSFORM: 'CODE_TRANSFORM',
  CONDITION: 'CONDITION',
  LOG_ACTION: 'LOG_ACTION',
  PDF_GENERATOR: 'pdfGenerator',
  // Discord
  DISCORD_SEND_MESSAGE: 'discordSendMessage',
  DISCORD_CREATE_CHANNEL: 'discordCreateChannel',
  DISCORD_DELETE_CHANNEL: 'discordDeleteChannel',
  DISCORD_CREATE_ROLE: 'discordCreateRole',
  DISCORD_DELETE_ROLE: 'discordDeleteRole',
  DISCORD_ADD_ROLE_TO_MEMBER: 'discordAddRoleToMember',
  DISCORD_REMOVE_ROLE_FROM_MEMBER: 'discordRemoveRoleFromMember',
  DISCORD: 'discord',
  // Google Sheets
  GOOGLE_SHEETS_TRIGGER: 'googleSheetsTrigger',
  GOOGLE_SHEETS_CREATE_SPREADSHEET: 'googleSheetsCreateSpreadsheet',
  GOOGLE_SHEETS_CREATE_WORKSHEET: 'googleSheetsCreateWorksheet',
  GOOGLE_SHEETS_DELETE_WORKSHEET: 'googleSheetsDeleteWorksheet',
  GOOGLE_SHEETS_READ_ROWS: 'googleSheetsReadRows',
  GOOGLE_SHEETS_APPEND_ROW: 'googleSheetsAppendRow',
  GOOGLE_SHEETS_UPDATE_ROW: 'googleSheetsUpdateRow',
  GOOGLE_SHEETS_DELETE_ROW: 'googleSheetsDeleteRow',
};

export const NODE_REGISTRY = {
  [NODE_TYPES.MANUAL_TRIGGER]: {
    type: NODE_TYPES.MANUAL_TRIGGER,
    category: 'TRIGGER',
    label: 'Manual Trigger',
    description: 'Triggers workflow execution manually via button click or API',
    icon: Zap,
    color: 'emerald',
    badgeColor: 'bg-emerald-500/10 text-emerald-400 border-emerald-500/20',
    defaultConfig: {},
  },
  [NODE_TYPES.WEBHOOK_TRIGGER]: {
    type: NODE_TYPES.WEBHOOK_TRIGGER,
    category: 'TRIGGER',
    label: 'Webhook Trigger',
    description: 'Triggers workflow when HTTP POST/GET request is received',
    icon: Webhook,
    color: 'purple',
    badgeColor: 'bg-purple-500/10 text-purple-400 border-purple-500/20',
    defaultConfig: {
      path: '/api/v1/webhooks/:token',
    },
  },
  [NODE_TYPES.SCHEDULE_TRIGGER]: {
    type: NODE_TYPES.SCHEDULE_TRIGGER,
    category: 'TRIGGER',
    label: 'Schedule (Cron)',
    description: 'Runs workflow automatically at recurring time intervals',
    icon: Clock,
    color: 'amber',
    badgeColor: 'bg-amber-500/10 text-amber-400 border-amber-500/20',
    defaultConfig: {
      cron: '0 * * * *',
    },
  },
  [NODE_TYPES.HTTP_REQUEST]: {
    type: NODE_TYPES.HTTP_REQUEST,
    category: 'ACTION',
    label: 'HTTP Request',
    description: 'Makes REST API calls (GET, POST, PUT, DELETE)',
    icon: Globe,
    color: 'blue',
    badgeColor: 'bg-blue-500/10 text-blue-400 border-blue-500/20',
    defaultConfig: {
      method: 'GET',
      url: 'https://jsonplaceholder.typicode.com/todos/1',
      headers: '{\n  "Content-Type": "application/json"\n}',
      body: '',
    },
  },
  [NODE_TYPES.DELAY]: {
    type: NODE_TYPES.DELAY,
    category: 'ACTION',
    label: 'Delay / Sleep',
    description: 'Pauses workflow execution for specified time',
    icon: Hourglass,
    color: 'amber',
    badgeColor: 'bg-amber-500/10 text-amber-400 border-amber-500/20',
    defaultConfig: {
      seconds: 2,
    },
  },
  [NODE_TYPES.CODE_TRANSFORM]: {
    type: NODE_TYPES.CODE_TRANSFORM,
    category: 'ACTION',
    label: 'JavaScript Code',
    description: 'Transforms payload using custom JavaScript function',
    icon: Code,
    color: 'cyan',
    badgeColor: 'bg-cyan-500/10 text-cyan-400 border-cyan-500/20',
    defaultConfig: {
      code: 'return {\n  transformed: true,\n  timestamp: new Date().toISOString(),\n  data: $input\n};',
    },
  },
  [NODE_TYPES.CONDITION]: {
    type: NODE_TYPES.CONDITION,
    category: 'LOGIC',
    label: 'If / Else Condition',
    description: 'Evaluates logic condition and branches workflow',
    icon: GitBranch,
    color: 'rose',
    badgeColor: 'bg-rose-500/10 text-rose-400 border-rose-500/20',
    defaultConfig: {
      field: '$prev.status',
      operator: 'equals',
      value: '200',
    },
  },
  [NODE_TYPES.LOG_ACTION]: {
    type: NODE_TYPES.LOG_ACTION,
    category: 'ACTION',
    label: 'Console Logger',
    description: 'Prints message and payload to execution log viewer',
    icon: Terminal,
    color: 'slate',
    badgeColor: 'bg-slate-500/10 text-slate-400 border-slate-500/20',
    defaultConfig: {
      message: 'Step execution completed successfully.',
    },
  },
  [NODE_TYPES.PDF_GENERATOR]: {
    type: NODE_TYPES.PDF_GENERATOR,
    category: 'Output',
    label: 'PDF Generator',
    description: 'Generate professional PDFs from workflow data. Supports invoices, certificates, reports, receipts, and custom HTML.',
    icon: FileOutput,
    color: 'violet',
    badgeColor: 'bg-violet-500/10 text-violet-400 border-violet-500/20',
    defaultConfig: {
      template: 'blank',
      fileName: 'document_{{now}}.pdf',
      pageSize: 'A4',
      orientation: 'portrait',
      outputMode: 'base64',
      content: '<h1>Hello {{trigger.body.name}}</h1>\n<p>Generated on {{now}}</p>',
    },
  },
  [NODE_TYPES.GOOGLE_SHEETS_TRIGGER]: {
    type: NODE_TYPES.GOOGLE_SHEETS_TRIGGER,
    category: 'TRIGGER',
    label: 'Google Sheets Trigger',
    description: 'Triggers workflow automatically whenever rows are added or updated in a Google Sheet',
    icon: Zap,
    color: 'emerald',
    badgeColor: 'bg-emerald-500/10 text-emerald-400 border-emerald-500/20',
    defaultConfig: { worksheetTitle: 'Sheet1', triggerEvent: 'newRow', pollingInterval: '30s', ignoreExistingRows: true, maxRows: 100 },
  },
  [NODE_TYPES.GOOGLE_SHEETS_CREATE_SPREADSHEET]: {
    type: NODE_TYPES.GOOGLE_SHEETS_CREATE_SPREADSHEET,
    category: 'Google Sheets',
    label: 'Google Sheets Create Spreadsheet',
    description: 'Create a brand-new Google Spreadsheet in Google Drive with initial worksheet',
    icon: FileOutput,
    color: 'emerald',
    badgeColor: 'bg-emerald-500/10 text-emerald-400 border-emerald-500/20',
    defaultConfig: { title: 'New Spreadsheet', worksheetTitle: 'Sheet1' },
  },
  [NODE_TYPES.GOOGLE_SHEETS_CREATE_WORKSHEET]: {
    type: NODE_TYPES.GOOGLE_SHEETS_CREATE_WORKSHEET,
    category: 'Google Sheets',
    label: 'Google Sheets Create Worksheet',
    description: 'Create a new worksheet tab inside an existing Google Spreadsheet',
    icon: Layers,
    color: 'emerald',
    badgeColor: 'bg-emerald-500/10 text-emerald-400 border-emerald-500/20',
    defaultConfig: { worksheetName: 'New Sheet', rowCount: 1000, columnCount: 26 },
  },
  [NODE_TYPES.GOOGLE_SHEETS_DELETE_WORKSHEET]: {
    type: NODE_TYPES.GOOGLE_SHEETS_DELETE_WORKSHEET,
    category: 'Google Sheets',
    label: 'Google Sheets Delete Worksheet',
    description: 'Delete a worksheet tab from an existing Google Spreadsheet',
    icon: Trash2,
    color: 'emerald',
    badgeColor: 'bg-emerald-500/10 text-emerald-400 border-emerald-500/20',
    defaultConfig: { worksheet: '' },
    requiresColumns: false,
    supportsColumnMapping: false,
  },
  [NODE_TYPES.GOOGLE_SHEETS_READ_ROWS]: {
    type: NODE_TYPES.GOOGLE_SHEETS_READ_ROWS,
    category: 'Google Sheets',
    label: 'Google Sheets Read Rows',
    description: 'Read rows from a Google Sheet into JSON format',
    icon: FileOutput,
    color: 'emerald',
    badgeColor: 'bg-emerald-500/10 text-emerald-400 border-emerald-500/20',
    defaultConfig: { range: 'A1:Z100', headerRow: 1, filterEmpty: true },
  },
  [NODE_TYPES.GOOGLE_SHEETS_APPEND_ROW]: {
    type: NODE_TYPES.GOOGLE_SHEETS_APPEND_ROW,
    category: 'Google Sheets',
    label: 'Google Sheets Append Row',
    description: 'Append row with column auto detection and variable mapping',
    icon: FileOutput,
    color: 'emerald',
    badgeColor: 'bg-emerald-500/10 text-emerald-400 border-emerald-500/20',
    defaultConfig: { range: 'Sheet1!A1', mappings: [] },
  },
  [NODE_TYPES.DISCORD_SEND_MESSAGE]: {
    type: NODE_TYPES.DISCORD_SEND_MESSAGE,
    category: 'Communication',
    label: 'Discord → Send Message',
    description: 'Send text, markdown, mentions, embeds, and TTS messages to a Discord channel',
    icon: MessageSquare,
    color: 'indigo',
    badgeColor: 'bg-indigo-500/10 text-indigo-400 border-indigo-500/20',
    defaultConfig: {
      credentialId: '',
      guildId: '',
      channelId: '',
      content: '',
      embeds: '',
      tts: false,
      replyToMessageId: '',
      suppressEmbeds: false,
    },
  },
  [NODE_TYPES.DISCORD_CREATE_CHANNEL]: {
    type: NODE_TYPES.DISCORD_CREATE_CHANNEL,
    category: 'Communication',
    label: 'Discord → Create Channel',
    description: 'Create a new Text Channel, Voice Channel, or Category in a Discord Server.',
    icon: FolderPlus,
    color: 'indigo',
    badgeColor: 'bg-indigo-500/10 text-indigo-400 border-indigo-500/20',
    defaultConfig: {
      credentialId: '',
      guildId: '',
      channelType: 0,
      name: '',
      topic: '',
      nsfw: false,
      slowmode: 0,
      parentId: '',
      bitrate: 64000,
      userLimit: 0,
    },
  },
  [NODE_TYPES.DISCORD_DELETE_CHANNEL]: {
    type: NODE_TYPES.DISCORD_DELETE_CHANNEL,
    category: 'Communication',
    label: 'Discord → Delete Channel',
    description: 'Delete an existing Discord channel using the Discord Bot Token.',
    icon: Trash2,
    color: 'rose',
    badgeColor: 'bg-rose-500/10 text-rose-400 border-rose-500/20',
    defaultConfig: {
      credentialId: '',
      guildId: '',
      channelId: '',
      confirmDelete: false,
    },
  },
  [NODE_TYPES.DISCORD_CREATE_ROLE]: {
    type: NODE_TYPES.DISCORD_CREATE_ROLE,
    category: 'Communication',
    label: 'Discord → Create Role',
    description: 'Create a new Discord role with custom color, hoist, mentionable permissions, and audit log reason.',
    icon: ShieldPlus,
    color: 'indigo',
    badgeColor: 'bg-indigo-500/10 text-indigo-400 border-indigo-500/20',
    defaultConfig: {
      credentialId: '',
      guildId: '',
      name: '',
      color: '#5865F2',
      hoist: false,
      mentionable: false,
      reason: '',
    },
  },
  [NODE_TYPES.DISCORD_DELETE_ROLE]: {
    type: NODE_TYPES.DISCORD_DELETE_ROLE,
    category: 'Communication',
    label: 'Discord → Delete Role',
    description: 'Delete an existing Discord role from a selected Discord server.',
    icon: ShieldX,
    color: 'rose',
    badgeColor: 'bg-rose-500/10 text-rose-400 border-rose-500/20',
    defaultConfig: {
      credentialId: '',
      guildId: '',
      roleId: '',
      reason: '',
      confirmDelete: false,
    },
  },
  [NODE_TYPES.DISCORD_ADD_ROLE_TO_MEMBER]: {
    type: NODE_TYPES.DISCORD_ADD_ROLE_TO_MEMBER,
    category: 'Communication',
    label: 'Discord → Add Role to Member',
    description: 'Add an existing Discord role to a selected member in a selected Discord server.',
    icon: UserPlus,
    color: 'indigo',
    badgeColor: 'bg-indigo-500/10 text-indigo-400 border-indigo-500/20',
    defaultConfig: {
      credentialId: '',
      guildId: '',
      userId: '',
      roleId: '',
      reason: '',
    },
  },
  [NODE_TYPES.DISCORD_REMOVE_ROLE_FROM_MEMBER]: {
    type: NODE_TYPES.DISCORD_REMOVE_ROLE_FROM_MEMBER,
    category: 'Communication',
    label: 'Discord → Remove Role from Member',
    description: 'Remove an existing Discord role from a selected member in a selected Discord server.',
    icon: UserMinus,
    color: 'rose',
    badgeColor: 'bg-rose-500/10 text-rose-400 border-rose-500/20',
    defaultConfig: {
      credentialId: '',
      guildId: '',
      userId: '',
      roleId: '',
      reason: '',
    },
  },
  [NODE_TYPES.DISCORD]: {
    type: NODE_TYPES.DISCORD,
    category: 'Communication',
    label: 'Discord → Send Message',
    description: 'Send text, markdown, mentions, embeds, and TTS messages to a Discord channel',
    icon: MessageSquare,
    color: 'indigo',
    badgeColor: 'bg-indigo-500/10 text-indigo-400 border-indigo-500/20',
    defaultConfig: {
      credentialId: '',
      guildId: '',
      channelId: '',
      content: '',
      embeds: '',
      tts: false,
      replyToMessageId: '',
      suppressEmbeds: false,
    },
  },
};



